### ISSUE TITLE
Constraints don't have accessible database ids

### ISSUE THREAD

**Issue by DJWalker42** [orppst/pst-api-service#1]
In order to edit-delete Constraints in front-end clients access to their database IDs is required. Currently, there is a JsonIgnore annotation on the '_id' member of the Constraints abstract base class meaning we cannot see the database id.

**Comment by pahjbo** [comment]
I have pushed a new proposalDM snapshot that does have the database ids - note that Constraint is now called ObservingConstraint (as constraint is an SQL reserved word)

**Comment by pahjbo** [comment]
I think that the latest proposalDM does solve this issue
