### ISSUE TITLE
A submitted proposal doesn't correctly reference cloned objects.

### ISSUE THREAD

**Issue by AllanEngland** [orppst/pst-api-service#14]
When a proposal is submitted to a cycle, the proposal and its child objects are correctly duplicated.  However, some of the references are not updated to these duplicates and point back to the source proposal's objects. 

I believe that the 'field' in observation and 'performance' in technicalGoal are dealt with correctly, but 'target' and 'technicalGoal' in observation are not.  This causes the overview page in the GUI to crash.

I'll continue to investigate if any other references are not updated correctly.

**Comment by AllanEngland** [comment]
I've checked through all the tables and I'm pretty sure the only one with problems is Observation.

**Comment by pahjbo** [comment]
I have updated the vo-dml tools to handle the contained references better (hopefully properly) It does require surrounding the lines where the clone is done with some code as below

```
model.createContext();
MyType cloned = new MyType(original);
cloned.updateClonedReferences();
```
