### ISSUE TITLE
Simbad to return a list of possible targets based on limited user input

### ISSUE THREAD

**Issue by DJWalker42** [orppst/pst-api-service#2]
The Simbad query we currently use in the API returns a single, requested target name only. This means a user of a front end client must supply a valid target name in order to get back the target details (coordinates etc.).  It would be better if we could have the API return a list of potential targets based on at least one character of user input, say, such that the user could select the one they want.  

Simbad itself offers different ways of querying its database such as proximity searches or by criterium constraints - see [here](https://simbad.u-strasbg.fr/simbad/sim-fid). We may also want to consider allowing users of our front ends access to some of this functionality.

**Comment by pahjbo** [comment]
I agree that we should probably write a front end only integration with Simbad - it will be much more responsive.

**Comment by DJWalker42** [comment]
Now obsolete as we have a frontend SIMBAD integration.
