### ISSUE TITLE
PI should be allowed to withdraw a previously submitted proposal

### ISSUE THREAD

**Issue by DJWalker42** [orppst/pst-api-service#58]
A PI should be able to withdraw a previously submitted proposal. For a straightforward implementation of this we should enforce the policy that withdrawals may only occur before the submission deadline.

**Comment by AllanEngland** [comment]
PI's can now list submitted proposals and try to withdraw them.  The withdrawal endpoint will only work if the current user is a PI on the proposal and no reviews exist (reviewers assigned?).  

It's possible that removing a submitted proposal from a cycle could leave some orphans in the database.  I've left this as a TODO for now 'cause it's tricky to investigate without GUI integration.
